name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: https://github.com/hvantran/project-management.git
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email "tranvanhoactk34@gmail.com"
          git config user.name "GitHub Actions - update external-endpoint-collector submodule"
          git add --all
          git commit -m "Update external-endpoint-collector submodules" || echo "No changes to commit"
          git push
